### ISSUE TITLE
Missing 2017 NAICS from MasterCrosswalk

### ISSUE THREAD

**Issue by catherinebirney** [USEPA/useeior#123]
@MoLi7 
The following 2017 NAICS are not mapped to 2012 NAICS

['21112', '21113', '238111', '238112', '238121', '238122', '238131', '238132', '238141', '238142', '238151', '238152', '238161', '238162', '238171', '238172', '238191', '238192', '238211', '238212', '238221', '238222', '238291', '238292', '238311', '238312', '238321', '238322', '238331', '238332', '238341', '238342', '238351', '238352', '238391', '238392', '238911', '238912', '238991', '238992', '4522', '45221', '4523', '45231', '51225', '5173', '51731', '53228']

**Comment by catherinebirney** [comment]
@MoLi7 I checked all listed NAICS and most are not valid NAICS 2017 codes. 

The codes that are valid:
'21112', '21113', '4522', '45221', '4523', '45231', '51225', '5173', '51731', '53228'

**Comment by MoLi7** [comment]
> @MoLi7 I checked all listed NAICS and most are not valid NAICS 2017 codes.
> 
> The codes that are valid:
> '21112', '21113', '4522', '45221', '4523', '45231', '51225', '5173', '51731', '53228'

Thanks @catherinebirney! I'm looking into it now.
PS. I hope you would feel better soon - they said drinking more water is helpful. 😄

**Comment by MoLi7** [comment]
It turns out that I created a full, 2-6 digit 2007-2012-2017 NAICS mapping but dropped the rows where the 3 codes are not the same, see [here](https://github.com/USEPA/useeior/blob/572bee63137ba71acc6f769a1e6e758df81d00dd/data-raw/MasterCrosswalk.R#L233-L238). Mostly the case was 2007==2012!=2017, so many 2017 codes were dropped.

It probably was useful before but does not seem right now, so I disabled it and found all these codes are included:
'21112', '21113', '4522', '45221', '4523', '45231', '51225', '5173', '51731', '53228'

If this makes sense to you, I will re-generate and push MasterCrosswalk2012 and MasterCrosswalk2007 to useeior master.
@catherinebirney @WesIngwersen

**Comment by catherinebirney** [comment]
@MoLi7 Makes sense to me, thanks for taking the time to figure out the issue!

**Comment by MoLi7** [comment]
Fixed by 996543653ea85014fa7c0d1d9919f2f66346422e and 1c41d7185c737c331ceda03072371945a9937ae2.

**Comment by WesIngwersen** [comment]
This looks fine, but I just want to be sure that if additional lines are added for instance with NAICS 2012 codes that correspond to original 2017 codes, that in our aggregation process with existing NAICS 2012 data that those sectors won't be double counted. Please just confirm., thanks.

**Comment by MoLi7** [comment]
There won't be double counting in flow aggregation, because `model$crosswalk` has dropped duplicated NAICS2012-to-BEA obs in [model initialization](https://github.com/USEPA/useeior/blob/1c41d7185c737c331ceda03072371945a9937ae2/R/InitializeModel.R#L13).
