### ISSUE TITLE
Add in margin impacts

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#13]
Create M and U matrices with additional impacts of margins

**Comment by MoLi7** [comment]
@WesIngwersen Determining margin_allocation table can be tricky: ideally, it should be commodity output ratios (because we are allocating margins), but if the model is an Industry model, we can only calculate industry output ratios, which means a getOutputRatio function cannot flexibly do the work. Unless we pre-calculate and save all output ratio tables for Commodity and Industry models, then pass part of them to margin_allocation. Is it worth doing it?

**Comment by MoLi7** [comment]
@WesIngwersen Scratched the previous comment, I created [this utility function](https://github.com/USEPA/useeior/blob/e591693a723b31b1237a0c37d265609057bc84e4/R/UtilityFunctions.R#L43-L78) to flexibly calculate output ratios.

**Comment by WesIngwersen** [comment]
@MoLi7 In the margin_allocation table, the idea was that the ratios would be like:  (x_481000)/sum(x_for all transportation sectors), so it would be passing a vector of sectors code to get the output for and dividing by the sum.  Since model object already has CommodityOutput and IndustryOutput saved, then its easy just to use that.
