### ISSUE TITLE
getMarginsTable: transform margins from Commodity to Industry format if specified by model

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#14]
@WesIngwersen Could you review this process [here](https://github.com/USEPA/useeior/blob/dd2cbe80cd537e1f741cfd4d87440bcb84021867/R/IOFunctions.R#L398-L405) to confirm the transformation is correct?

If marginsource=="final consumer", the [vector %*% matrix](https://github.com/USEPA/useeior/blob/dd2cbe80cd537e1f741cfd4d87440bcb84021867/R/IOFunctions.R#L403) does not return correct results for ProducerValue.

**Comment by MoLi7** [comment]
@WesIngwersen Please also note that I dropped the V sectors in MarginsTable using [this code](https://github.com/USEPA/useeior/blob/2c9a80cb81957d470bc5592c87a72517b36c759b/R/IOFunctions.R#L395-L396).

**Comment by WesIngwersen** [comment]
The setup of the code within the [if statement] for handing industry models (https://github.com/USEPA/useeior/blob/master/R/IOFunctions.R#L400) should be improved.

I suggest after calculating Margins_Industry to merge it with the MarginsTable instead of assigning MarginsTable the new MarginsTable_Industry$ProducersValue column

**Comment by MoLi7** [comment]
Merging sounds good, it will return a Margins Table with several industry sectors having zeros in Transportation, Wholesale, Retail and having PurchaserValue=ProducerValue.
