### ISSUE TITLE
Warning in writeModeltoXLSX

### ISSUE THREAD

**Issue by bl-young** [USEPA/useeior#150]
```
>writeModeltoXLSX(model, 'C:/Users/BYoung/AppData/Local/useeior/')
the condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be used
```

**Comment by MoLi7** [comment]
I cannot replicate your example...
`> writeModeltoXLSX(model, '/Users/moli/Desktop')`
`2021-08-04 11:28:35 INFO::Model matrices written to Excel workbook (.xlsx) in //Users/moli/Desktop.`

Which step in `writeModeltoXLSX` would you think is causing such warning?

**Comment by mwfrost** [comment]
@MoLi7 Use `warnings()` and I think you will see what Ben is referring to.

The `class()` method does not always return a single class name. Rather, it returns a list of all the classes that an R object inherits from. Try `class(matrix(1:6, 2,3))` for an example.

Because some of the objects in `USEEIOtoXLSX_ls` are of the `matrix` data type, the `class()` method returns `"matrix" "array"`, and both objects get passed to the `if()` condition here:
https://github.com/USEPA/useeior/blob/e01d189171d980e05530dce323f3ec5a89aecf92/R/WriteModel.R#L81

So `class(USEEIOtoXLSX_ls[["D"]])`, for example, returns `"matrix" "array"`, and therefore `class(USEEIOtoXLSX_ls[["D"]]) %in% c("matrix", "data.frame")` returns `TRUE FALSE`. The `if()` function only takes a single argument, so it ignores the second element in the `TRUE FALSE` pair. It happens to work, but it throws a warning. 

Instead of using `class(USEEIOtoXLSX_ls[["D"]]) %in% c("matrix", "data.frame")` , one solution would be to use 
```{r}
( USEEIOtoXLSX_ls[[n]] %>% is("matrix")  | USEEIOtoXLSX_ls[[n]] %>% is("data.frame") )
```

Here's a deep dive into the topic: https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/

**Comment by mwfrost** [comment]
Code used for testing, saving here for lack of a better file:
```
matrices <- c("V", "U", "U_d", "A", "A_d", "B", "C", "D", "L", "L_d",
              "M", "M_d", "N", "N_d", "Rho", "Phi")

USEEIOtoXLSX_ls <- model[matrices]

for (n in names(USEEIOtoXLSX_ls)) {
  print(n)
  print(
    class(USEEIOtoXLSX_ls[[n]])
  )
  print(
    class(USEEIOtoXLSX_ls[[n]])%in%c("matrix", "data.frame")
  )
  
  print(
    ( USEEIOtoXLSX_ls[[n]] %>% is("matrix")  | USEEIOtoXLSX_ls[[n]] %>% is("data.frame") )
  )
}
```

**Comment by MoLi7** [comment]
@mwfrost thanks for looking into this!

Somehow `class(matrix(1:6, 2,3))` only returns `matrix` in my R setup/environment (version 3.6.3), but I can see that `D` is both matrix and array:
> is.matrix(USEEIOtoXLSX_ls[["D"]])
[1] TRUE
> is.array(USEEIOtoXLSX_ls[["D"]])
[1] TRUE

In your suggestion `( USEEIOtoXLSX_ls[[n]] %>% is("matrix")  | USEEIOtoXLSX_ls[[n]] %>% is("data.frame") )`, I suppose we need to define `%>%` first?

Maybe we can use `(is.matrix(USEEIOtoXLSX_ls[[n]]) | is.data.frame(USEEIOtoXLSX_ls[[n]]))` instead, your thoughts?

**Comment by mwfrost** [comment]
Nice to see that this was fixed. I load the `magrittr` library in my environment out of habit, so the `%>%` pipe is always defined, but you are correct, @MoLi7  -- that's not the case in the application code.
