### ISSUE TITLE
Some values are larger in `A_d` than in `A`?

### ISSUE THREAD

**Issue by msrocka** [USEPA/useeior#169]
Using the current `master` branch, I just built the matrices of the `USEEIOv2.0.1` model and exported them via:

```r
model <- buildModel('USEEIOv2.0.1')
writeModelforAPI(model, "C:/Users/ms/Desktop/USEEIOv2.0.1")
```

When I calculate `A - A_d` I get some negative result patterns, especially for the transport inputs, which means that the values in `A_d` are larger here?:

![image](https://user-images.githubusercontent.com/3520062/139424109-a7d620d4-048a-4f6d-a67e-71c378b74d95.png)

Shouldn't always `A_d < A` as `A_d + A_non_domestic = A`, or did I something wrong? 

Here my script with which I checked this:

```py
import os
import struct

import numpy
import pandas

model_dir = 'C:/Users/ms/Desktop/USEEIOv2.0.1/build/data/USEEIOv2.0.1'
check_dir = 'C:/Users/ms/Desktop/d_checks'


def read_matrix(matrix: str) -> numpy.ndarray:
    matrix_path = os.path.join(model_dir, matrix + '.bin')
    with open(matrix_path, 'rb') as f:
        rows = struct.unpack('<i', f.read(4))[0]
        cols = struct.unpack('<i', f.read(4))[0]
        return numpy.memmap(matrix_path, mode='c', dtype='<f8',
                            shape=(rows, cols), offset=8, order='F')


def write_csv(matrix, data: numpy.ndarray):
    matrix_path = os.path.join(check_dir, matrix + '.csv')
    df = pandas.DataFrame(data)
    df.to_csv(matrix_path)


def main():
    os.makedirs(check_dir)
    for m in ['A', 'L', 'N']:
        total = read_matrix(m)
        domestic = read_matrix(f'{m}_d')
        non_domestic = total - domestic
        write_csv(m, total)
        write_csv(f'{m}_d', domestic)
        write_csv(f'{m}_nond', non_domestic)


if __name__ == '__main__':
    main()
```

Thanks!

**Comment by MoLi7** [comment]
Because we included `ImportCost` in `DomesticUse` calculation:
https://github.com/USEPA/useeior/blob/a5ff886055cf6971446ba25121b66e4ea8aa66f3/R/IOFunctions.R#L192-L196
As a result, `DomesticUse` is no longer simply `Use` - `Import`, instead it is:
https://github.com/USEPA/useeior/blob/a5ff886055cf6971446ba25121b66e4ea8aa66f3/R/IOFunctions.R#L207
Given the original BEA IO accounts, `ImportCost` of transportation sectors 481000-484000 are often > 0, so adding it to `DomesticUse` leads to `DomesticUse` > `Use` and then `A_d` > `A` for those sectors.
In fact, in your `A - A_d`, you will find rows "2122A0" "4200ID" "492000" "5241XX" also have some negative values, only because `ImportCost` of these commodities are > 0.

**Comment by msrocka** [comment]
Many thanks @MoLi7 . This is interesting, but shouldn't the import costs be also added to the normal use table then so that they are also included in `A`?

**Comment by MoLi7** [comment]
Update: we modified our methodology to exclude `ImportCost`, also referred to as`InternationalTradeAdjustment`, from `DomesticUse` calculation. Instead, `InternationalTradeAdjustment` is only declared as a model component `model$mu` for transparency. And now `DomesticUse` = `Use` - `Import`, which should lead to `A` >= `A_d` for all commodities.

@msrocka see https://github.com/USEPA/useeior/pull/175 for details.

**Comment by MoLi7** [comment]
This issue is resolved by PR https://github.com/USEPA/useeior/pull/175.
