### ISSUE TITLE
All BEA levels needed in model$crosswalk

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#81]
@WesIngwersen @bl-young @jvendries 
I notice [`model$crosswalk`](https://github.com/USEPA/useeior/blob/ef270925b0c29a287f5abdd8c64a732b727ef982/R/LoadIOTables.R#L12-L14) now only has two columns (one BEA and one NAICS), but sometimes all BEA levels (or at least two levels) are needed in particular circumstances, such as [aggregating sat tables](https://github.com/USEPA/useeior/blob/ef270925b0c29a287f5abdd8c64a732b727ef982/R/SatelliteFunctions.R#L127) and visualization. Specifically, I need to know the mapping between BEA_Sector and BEA_Detail to plot coefficients of USEEIO2.0 with proper colors.

I understand that having only two columns makes it easier in many cases in terms of column indexing, but I figure the inclusiveness of `model$crosswalk` would be the priority overall. **Please let me know your thoughts.**

P.S. There are a few places in the code where `useeior::Mastercrosswalk2012` is still called and used, I'm not sure if all can be directly replaced by `model$crosswalk` because some are utility functions where `model` is not a suitable parameter. I need to take a closer look at it.

**Comment by WesIngwersen** [comment]
Yes I actually think we need the other sectors for writeSectorCrosswalktoAPI unless that is not model dependent

**Comment by bl-young** [comment]
model$Crosswalk is the version that gets updated for disaggregation. I think in some cases it makes sense to go back to the original (in cases where BEA data is being accessed such as in `getMarginsTable` [here](https://github.com/USEPA/useeior/blob/master/R/IOFunctions.R#L199))

I can imagine that when aggregating a satellite table for use in a summary model, it would be good to have the master$crosswalk show all levels of detail. I hadn't really considered a disaggregated model for a summary model, but I think its likely to be a use case.

I think the solution here is to make the model crosswalk have all BEA levels, and shrink it down when its needed such as in `mapFlowTotalsbySectorandLocationfromNAICStoBEA` [here](https://github.com/USEPA/useeior/blob/v2-alpha/R/SatelliteFunctions.R#L14)

In visualization, I expect you'll need to use model$crosswalk otherwise the disaggregated sectors won't show up.

**Comment by MoLi7** [comment]
@WesIngwersen @bl-young thanks for your feedbacks!

I think we've discussed and agreed to use `model$crosswalk` throughout the package regardless of disaggregation, therefore in the two examples you brought up, @bl-young , we can simply use `model$crosswalk` because `model` is a parameter in the functions. Let us coordinate on making `model$crosswalk` have all BEA levels since changes will be made in `buildEEIOModel`, [`NAICSSectorCW`](https://github.com/USEPA/useeior/blob/ef270925b0c29a287f5abdd8c64a732b727ef982/R/DisaggregateFunctions.R#L692), and throughout the package.

**Comment by WesIngwersen** [comment]
@MoLi7  can we close this now?

**Comment by MoLi7** [comment]
@WesIngwersen if it's okay, I'd like to close this after @bl-young and I complete all necessary modifications.

**Comment by WesIngwersen** [comment]
@bl-young @MoLi7 Something related is for the writerSectorCrosswalktoAPI. Thats a crosswalk for API users to use to go from a specific model schema to NAICS levels. A models schema is defined in the models.csv. For useeiov2, it doesnt have a defined schema now because of the disaggregation. It needs to have a column in that sectorcrosswalk so users can relate that model to NAICS

**Comment by MoLi7** [comment]
After a series of changes by @bl-young and myself, `model$crosswalk` is complete now.

@WesIngwersen I'm about to replace MasterCrosswalk2012 with `model$crosswalk` in writeSectorCrosswalkforAPI. Per your comment, I will add an empty ModelSchema column to `model$crosswalk` for now, is that what you want to have there?

For future model schemas, I imagine they can be defined in modelname.yml and will be available for referencing need like this?
