### ISSUE TITLE
Reconsider IO source of commodity output, q

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#91]
https://github.com/USEPA/useeior/blob/7a42b122cef30dddc00ea10030c04bc200ad2d19/R/LoadIOTables.R#L31

Currently the choice for q is the Use table. In the PRO price tables, q in Make ~ q in Use
but in the PUR model, q in Make does not equal Use
In that model, q would be more appropriate in most cases to be taken from Make, because of market shares calculation would need to use that q

**Comment by WesIngwersen** [comment]
One case in which such a change would not be if taking from the Make would be in the validation check,  q = UseTransactions + FinalDemand

**Comment by MoLi7** [comment]
We can modify `loadIOData` to get q from Make for PUR model, but it will lead to S00402 (used and secondhand goods) and S00300 (noncomparable imports) having zeros in q since these two are not industry-produced commodities. As a result, the market shares calculation will be inviable because of the zeros in q.

**Comment by WesIngwersen** [comment]
Let's hold off for now until I know that we need a PUR model.
